# Generated by Django 5.1.1 on 2024-10-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
