# Generated by Django 5.1.2 on 2024-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
