# Generated by Django 5.1.2 on 2024-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=30)),
                ('image_blog', models.ImageField(blank=True, null=True, upload_to='blogger')),
            ],
        ),
    ]
